# base
author: Drake Leung
author_url: https://github.com/DrakeLeung
theme_name: mmnn
theme_url: https://github.com/DrakeLeung/hexo-theme-mmnn

favicon: images/favicon.ico

# render sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

#about
social:
  avantar: images/about.png
  github: https://github.com/DrakeLeung
  weibo: http://weibo.com/cha12chalyc


# analytics
google_analytics: UA-63900271-1
baidu_analytics: true


# navs
navs:
  Home: /
  Archives: archives